In [1]:
import numpy as np

In [2]:
#creation of 1D numpy array:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
#creation of 2D numpy array
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [7]:
#creating array from random integers
np.random.randint(20,100,5)

array([99, 22, 26, 71, 71])

In [43]:
#get evenly spaced 'num' numbers within range
a=np.array([1,2,3,4,5,6,7,8])
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [34]:
#arange function :similar like range function but can also take float in steps
np.arange(0,10,2.5),list(range(1,10,2))

(array([0. , 2.5, 5. , 7.5]), [1, 3, 5, 7, 9])

In [37]:
#length of numpy array
a=np.array([[1,2],[3,4]])
len(a),a.size,a.shape

(2, 4, (2, 2))

In [38]:
#checking dimensions of array
a=np.array([1,2])
a.ndim

1

In [45]:
#slicing
a=np.array([1,2,3,4,5,6,7,8])

array([8, 7, 6, 5, 4, 3, 2, 1])

In [48]:
a[::-1],a[5:]

(array([8, 7, 6, 5, 4, 3, 2, 1]), array([6, 7, 8]))

In [62]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [64]:
a[0]

array([1, 2, 3, 4])

In [63]:
a[:,0:2]

array([[1, 2],
       [5, 6]])

In [65]:
#copying numpy array since it is mutable
b=a.copy()
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [241]:
#reversing the array:
a=np.array([1,2,3,4,5,6,7,8])
a[::-1],np.flip(a)

(array([8, 7, 6, 5, 4, 3, 2, 1]), array([8, 7, 6, 5, 4, 3, 2, 1]))

In [78]:
#sorting the numpy array
a=np.array([10,4,1,2,3,4,5,6,7,8])
a.sort()
a

array([ 1,  2,  3,  4,  4,  5,  6,  7,  8, 10])

In [79]:
#sorting in descending order use negative indexing
a=np.array([10,4,1,2,3,4,5,6,7,8])
a.sort()
a[::-1]

array([10,  8,  7,  6,  5,  4,  4,  3,  2,  1])

In [198]:
#statistical values
a=np.array([1,2,3,4,5,6,7,8])
a.mean(),a.max(),a.min(),a.std(),a.var(),a.sum(),np.median(a)

(4.5, 8, 1, 2.29128784747792, 5.25, 36, 4.5)

In [91]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b.max(),b.mean()

(8, 4.5)

In [97]:
#unique elements in numpy array
a=np.array([1,2,3,4,1,2,3,4,5,6,7,8])
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [100]:
#total number of unique values
len(np.unique(a))

8

In [99]:
#value counts of values
np.unique(a,return_counts=True)

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([2, 2, 2, 2, 1, 1, 1, 1], dtype=int64))

In [106]:
#reshape an array
a=np.array([1,2,3,4,1,2,3,4,5,6,7,8])
a.reshape(3,-1)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [107]:
#flatten the 2d array
b=np.array([[1,2,3,4],[5,6,7,8]])
b.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [172]:
a=np.array([1,2,3])
a.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [163]:
a=np.array([1,2,3])
a+10,a*2

(array([11, 12, 13]), array([2, 4, 6]))

In [166]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [167]:
b.T

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [186]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [189]:
#row wise addition
b.sum(axis=1)

array([10, 26])

In [190]:
#column wise sum
b.sum(axis=0)

array([ 6,  8, 10, 12])

In [2]:
#diagonal of a mamtrix
matrix=np.reshape(np.random.randint(10,50,25),newshape=(5,5))
matrix

array([[45, 19, 29, 21, 34],
       [26, 35, 21, 18, 29],
       [15, 31, 29, 26, 20],
       [44, 33, 26, 25, 23],
       [15, 30, 41, 44, 41]])

In [5]:
matrix.diagonal()

array([45, 35, 29, 25, 41])

In [4]:
np.flipud(matrix)

array([[15, 30, 41, 44, 41],
       [44, 33, 26, 25, 23],
       [15, 31, 29, 26, 20],
       [26, 35, 21, 18, 29],
       [45, 19, 29, 21, 34]])

In [3]:
matrix[::-1]

array([[15, 30, 41, 44, 41],
       [44, 33, 26, 25, 23],
       [15, 31, 29, 26, 20],
       [26, 35, 21, 18, 29],
       [45, 19, 29, 21, 34]])

### manipulating numpy array

In [108]:
#adding elements

In [110]:
a=np.array([1,2,3,4])
np.append(a,5)

array([1, 2, 3, 4, 5])

In [114]:
np.insert(a,4,99)

array([ 1,  2,  3,  4, 99])

In [ ]:
#for 2d:

In [142]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [145]:
np.append(b,np.array([[99],[98]]),axis=1)   

array([[ 1,  2,  3,  4, 99],
       [ 5,  6,  7,  8, 98]])

In [147]:
np.append(b,np.array([[99,98,97,97]]),axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [99, 98, 97, 97]])

In [194]:
#using hstack and vstack for adding elements 
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [199]:
c=np.array([0,0,0,0])
np.vstack([b,c])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 0, 0, 0]])

In [203]:
c=np.array([0,0]).reshape(-1,1)
np.hstack([b,c])

array([[1, 2, 3, 4, 0],
       [5, 6, 7, 8, 0]])

In [115]:
#removing elements from numpy array:
a=np.array([10,20,30,40])
np.delete(a,0)

array([20, 30, 40])

In [120]:
#remove multiple elements
a=np.array([10,20,30,40])
np.delete(a,[1,2])

array([10, 40])

In [121]:
a=np.array([10,20,30,40])
np.delete(a,np.arange(1,3))

array([10, 40])

In [149]:
b=np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [151]:
np.delete(b,np.array([[3],[3]]),axis=1)

array([[1, 2, 3],
       [5, 6, 7]])

In [155]:
b=np.array([[1,2],[5,6],[3,4]])
b

array([[1, 2],
       [5, 6],
       [3, 4]])

In [157]:
np.delete(b,np.array([[2]]),axis=0)

array([[1, 2],
       [5, 6]])

In [342]:
#update elements:
a=np.array([10,20,30,40])
a[a==20]=99
a

array([10, 99, 30, 40])

In [347]:
#index of an element
np.where(a==40)[0][0]

3

In [206]:
#filter elements
a=np.array([10,20,30,40])
a[a>25]

array([30, 40])

In [210]:
a=np.array([10,20,30,40,41])
a[(a>25) & (a%2!=0)]

array([41])

In [214]:
a=np.array([11,13,10,20,30,40,41])
a[(a>30) | (a%2==1)]

array([11, 13, 40, 41])

In [230]:
a=np.array([10,20,30,40])
index=np.where(a>25)
index

(array([2, 3], dtype=int64),)

In [231]:
a[index]

array([30, 40])

In [238]:
#index of top 5 largest elements in numpy array
a=np.array([6,3,9,1,3,21,9,67,34])
a.argsort()[::-1][:5]

array([7, 8, 5, 6, 2], dtype=int64)

In [249]:
a=np.array([6,3,9,1,3,21,9,67,34])
np.where(a>20,a,'no')

array(['no', 'no', 'no', 'no', 'no', '21', 'no', '67', '34'], dtype='<U11')

In [250]:
arr1=np.array([15,20,31,40])
arr2=np.array([1,1,36,2])
np.where(arr1>arr2,arr1,arr2)

array([15, 20, 36, 40])

In [251]:
arr1=np.array([15,20,31,40])
arr2=np.array([1,1,36,2])
np.where(arr1>arr2)

(array([0, 1, 3], dtype=int64),)

In [255]:
b=np.array([1,6,7,8,6,7,6,9,7,15])
c=np.bincount(b)
print(c)

[0 1 0 0 0 0 3 3 1 1 0 0 0 0 0 1]


In [258]:
a=np.array([1,2,3]).reshape(-1,1)
b=np.array([4,5,6]).reshape(-1,1)
a,b

(array([[1],
        [2],
        [3]]),
 array([[4],
        [5],
        [6]]))

In [265]:
np.c_[a,b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [267]:
np.hstack([a,b])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [359]:
#loading a csv file from numpy
np.genfromtxt("DS1_C4_S5_Sales_Data_Concept.csv",delimiter=",")[:4]

array([[ nan,  nan],
       [ nan, 185.],
       [ nan, 134.],
       [ nan, 126.]])

### Two lists

In [178]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
a+b,a-b,a/b,a*b

(array([11, 22, 33, 44]),
 array([ 9, 18, 27, 36]),
 array([10., 10., 10., 10.]),
 array([ 10,  40,  90, 160]))

In [204]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [205]:
a+b,a//b

(array([[ 6,  8],
        [10, 12]]),
 array([[0, 0],
        [0, 0]]))

In [181]:
a=np.array([10,20,30,40]).reshape(2,2)
b=np.array([1,2,3,4]).reshape(2,2)
a,b

(array([[10, 20],
        [30, 40]]),
 array([[1, 2],
        [3, 4]]))

In [182]:
#matrix multiplication
a@b

array([[ 70, 100],
       [150, 220]])

In [192]:
#concating two array
a=np.array([10,20,30,40])
b=np.array([1,2,3,4])
np.concatenate([a,b])

array([10, 20, 30, 40,  1,  2,  3,  4])

In [193]:
np.append(a,b)

array([10, 20, 30, 40,  1,  2,  3,  4])

In [278]:
#percentiles
a=np.array([10,20,30,40,50,60,70,15,25,35])
np.percentile(a,25)

21.25

In [280]:
np.median(a),np.percentile(a,50)

(32.5, 32.5)

In [282]:
np.nan

nan

In [285]:
#looping over numpy array
for i in a:
    print(i,end=" ")

10 20 30 40 50 60 70 15 25 35 

In [292]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [293]:
#save as csv
a.tofile("sumne.csv",sep=" ")

In [297]:
#index of the max and min values
a=np.array([10,20,30,40,50,60,70,15,25,35])
a.argmax(),a.argmin()

(6, 0)

In [7]:
a=np.array([10,20,30,40,50,60,70,70,15,25,35])
np.where(a==max(a))

(array([6, 7], dtype=int64),)

In [294]:
#array to list
a.tolist()

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

In [332]:
#ravle vs flatten

In [333]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [334]:
ra=np.ravel(a)
ra

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [335]:
fl=a.flatten()
fl

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [336]:
fl[0]=99
fl

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [337]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [338]:
ra[0]=99
ra

array([99,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [339]:
a

array([[99,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
#we can see that both flatten and ravel gives the 1D array 
#but the difference is if we change the value in ravel array, then original 2d array will also be changed
#ravel is faster than flatten
#flatten creates the copy of the array but ravel gives the view of original array

1. Reverse a 4x4 matrix

In [11]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [12]:
a.flatten()[::-1].reshape(4,4)

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])